apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactnative4-ingress
spec:
  rules:
    - host: reactnative4-mobile1-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reactnative4
                port: 
                  number: 80
  tls:
  - hosts:
    - reactnative4-mobile1-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: reactnative4
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: reactnative4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactnative4
  labels:
    app: reactnative4
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reactnative4
  template:
    metadata:
      labels:
        app: reactnative4
    spec:
      containers:
      - name: reactnative4
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/reactnative4:{image-tag}
        ports:
        - containerPort: 80